### ISSUE TITLE
UI Update: Splash Screen Text Change.

### ISSUE THREAD

**Issue by HeySitam** [HeySitam/CovidHelp#20]
## Description: 
- Change the text from `Need Help?` to `CovidHelp`
## Where to change :
![244172939_192965979584893_5995018542265692356_n](https://user-images.githubusercontent.com/76570320/135724123-77bdec82-1d88-46cb-95fe-241654583ed5.jpg)
## PR Instruction:
- Issue will be assigned on a first come first serve basis. 
- If you are thinking to make a pr then at first be sure to get assigned.
- before pushing your PR please make sure to fetch upstream.
- your pr should be pushed on the `develop` branch only.

**Comment by trybick** [comment]
Hi I can do this 👋

**Comment by HeySitam** [comment]
sure go for it.

**Comment by trybick** [comment]
PR opened #21
