### ISSUE TITLE
UI Update: Add Animation in Splash Screen.

### ISSUE THREAD

**Issue by HeySitam** [HeySitam/CovidHelp#22]
## Description:
- Add animation to the elements of the splash screen.
- Make it cooler and attractive 😋
## Here is the static Splash Screen :
![243377462_374645797662625_3825529616698737907_n](https://user-images.githubusercontent.com/76570320/135725052-4bfa80e9-3e54-4902-9280-c8c953f450c2.jpg)

## PR Instruction:
- Issue will be assigned on a first come first serve basis.
- If you are thinking to make a pr then at first be sure to get assigned.
- before pushing your PR please make sure to fetch upstream.
- your pr should be pushed on the `develop` branch only.
- try to complete your assigned task within 3 to 5 days and if you need more time then please let me know. As the program has limited time only so please try to complete as fast as you can.

**Comment by ritviksharma3** [comment]
Hi, Can you assign this to me?

**Comment by SiddyDevelops** [comment]
Hello sir, I would like to work on this issue. Can you please assign this to me?

**Comment by SiddyDevelops** [comment]
@sitamadex11 Sir please assign me this issue so I can create a PR. Thank you.

**Comment by HeySitam** [comment]
sure go for it.

**Comment by SiddyDevelops** [comment]
I have generated PR #58. Please review it. Thank you.

**Comment by SiddyDevelops** [comment]
@sitamadex11, I have generated PR #58. Please review it. Thank you.
