### ISSUE TITLE
BUG: the text from dialog box is not copying to the mail 

### ISSUE THREAD

**Issue by HeySitam** [HeySitam/CovidHelp#23]
## Description:
- In `Contact Us` section, when we try to send a mail then the entered text from dialog box is not copying into the text.
## Demo of problem :

https://user-images.githubusercontent.com/76570320/135729278-56e4a340-880e-428c-b270-9857642deb6a.mp4

## PR Instruction:
- Issue will be assigned on a first come first serve basis.
- If you are thinking to make a pr then at first be sure to get assigned.
- before pushing your PR please make sure to fetch upstream.
- your pr should be pushed on the `develop` branch only.
- try to complete your assigned task within 3 to 5 days and if you need more time then please let me know. As the program has limited time only so please try to complete as fast as you can.

**Comment by pgonzazalez** [comment]
Hi! Could I work on this issue? 😊

**Comment by HeySitam** [comment]
Sure go for it.

**Comment by Biren-Nayak** [comment]
Is this still open?

**Comment by HeySitam** [comment]
@Bondcoder any update?

**Comment by cdhiraj40** [comment]
@sitamadex11 you can assign me i will make PR in some time thanks :)
