### ISSUE TITLE
New Feature: Add a Privacy Policy section in the Navigation Drawer.

### ISSUE THREAD

**Issue by HeySitam** [HeySitam/CovidHelp#25]
## Description:
- Add a new menu item named `Privacy Policy` in the navigation drawer before `Logout`.
- when it is clicked, open the below-given link inside the app using a WebView
## Link to be opened:
https://covidhelp-3.flycricket.io/privacy.html

## PR Instruction:
- Issue will be assigned on a first come first serve basis.
- If you are thinking to make a pr then at first be sure to get assigned.
- before pushing your PR please make sure to fetch upstream.
- your pr should be pushed on the `develop` branch only.
- try to complete your assigned task within 3 to 5 days and if you need more time then please let me know. As the program has limited time only so please try to complete as fast as you can.
- With your PR try to send a screenshot or screen recording of your work

**Comment by mayorjay** [comment]
@sitamadex11 I will like to work on this, if that's okay

**Comment by HeySitam** [comment]
sure go for it.
