### ISSUE TITLE
UI: Update the Vaccine Status list item's UI

### ISSUE THREAD

**Issue by HeySitam** [HeySitam/CovidHelp#27]
## Description:
- Update the  Vaccine Status list item's UI. Make it more attractive. and with your PR try to send a screenshot or screen recording of your work. 
## Existing UI :
![Vaccine status list](https://user-images.githubusercontent.com/76570320/135730223-116132c6-fc42-4ad2-98f3-9bb83e73a645.jpg)

## PR Instruction:
- Issue will be assigned on a first come first serve basis.
- If you are thinking to make a pr then at first be sure to get assigned.
- before pushing your PR please make sure to fetch upstream.
- your pr should be pushed on the `develop` branch only.
- try to complete your assigned task within 3 to 5 days and if you need more time then please let me know. As the program has limited time only so please try to complete as fast as you can.
- With your PR try to send a screenshot or screen recording of your work

**Comment by pratik9315** [comment]
Hey there! 
Can I work on this issue if its alright?

**Comment by HeySitam** [comment]
sure you can work on this issue.

**Comment by pratik9315** [comment]
Hey @sitamadex11
I have made a pull request in #81
