### ISSUE TITLE
feature update: Call volunteers directly from app with handling permission. 

### ISSUE THREAD

**Issue by HeySitam** [HeySitam/CovidHelp#50]
## Description:
- In the `Volunteers` section, make calls to volunteers directly from the app.
- manage run time permission.
## Existing UI :
![volunteer list](https://user-images.githubusercontent.com/76570320/135769558-154f0740-7484-4185-993c-cd1c570b2266.jpg)

## PR Instruction:
- Issue will be assigned on a first come first serve basis.
- If you are thinking to make a pr then at first be sure to get assigned.
- before pushing your PR please make sure to fetch upstream.
- your pr should be pushed on the `develop` branch only.
- try to complete your assigned task within 3 to 5 days and if you need more time then please let me know. As the program has limited time only so please try to complete as fast as you can.
- With your PR try to send a screenshot or screen recording of your work

**Comment by shivamparihar12** [comment]
Hi, I would like to work on this issue.

**Comment by HeySitam** [comment]
sure go for it
