### ISSUE TITLE
feature update: Send Message to the volunteers directly from app with handling permission.

### ISSUE THREAD

**Issue by HeySitam** [HeySitam/CovidHelp#51]
## Description:
- In the `Volunteers` section, make messages to volunteers directly from the app.
- manage run time permission.
## Existing UI :
![volunteer list](https://user-images.githubusercontent.com/76570320/135769628-faa8e369-639e-4b97-ba2d-bc61ada80468.jpg)

## PR Instruction:
- Issue will be assigned on a first come first serve basis.
- If you are thinking to make a pr then at first be sure to get assigned.
- before pushing your PR please make sure to fetch upstream.
- your pr should be pushed on the `develop` branch only.
- try to complete your assigned task within 3 to 5 days and if you need more time then please let me know. As the program has limited time only so please try to complete as fast as you can.
- With your PR try to send a screenshot or screen recording of your work

**Comment by ghost** [comment]
Hello. Do you mean redirect to message app via intent?

**Comment by HeySitam** [comment]
Actually, this functionality is already there. I want to send message directly from the app without opening the message app.

**Comment by prashant7139** [comment]
@sitamadex11 I would like to work on this issue .

**Comment by HeySitam** [comment]
@prashant7139 sure
