### ISSUE TITLE
UI Update: Change the text

### ISSUE THREAD

**Issue by HeySitam** [HeySitam/CovidHelp#52]
## Description:
- In `Resources` section, change the card view's title from `A project for supplying Oxygen Cylinder in your home` to `project Oxygen`.
## Where need to change?
![resources](https://user-images.githubusercontent.com/76570320/135769942-345d7685-aaab-4229-ae41-25672b2a297c.jpg)

## PR Instruction:
- Issue will be assigned on a first come first serve basis.
- If you are thinking to make a pr then at first be sure to get assigned.
- before pushing your PR please make sure to fetch upstream.
- your pr should be pushed on the `develop` branch only.
- try to complete your assigned task within 3 to 5 days and if you need more time then please let me know. As the program has limited time only so please try to complete as fast as you can.
- With your PR try to send a screenshot or screen recording of your work

**Comment by prashant7139** [comment]
@sitamadex11 I will like to work on this .

**Comment by prashant7139** [comment]
@sitamadex11 I would like to work on this issue.

**Comment by Angel2001-programmer** [comment]
I would like to work on this issue.

**Comment by HeySitam** [comment]
@prashant7139 you start working.
@Angel2001-programmer as I am assigning the issue on a first come first serve basis therefore please look into other issues. soon I will create more issues also.
