### ISSUE TITLE
UI: Update the View Profile UI

### ISSUE THREAD

**Issue by HeySitam** [HeySitam/CovidHelp#53]
## Description:
- Update the existing UI of `View Profile` Section. Make the UI more attractive.✌
## Existing Ui:
![View Profile](https://user-images.githubusercontent.com/76570320/135770098-919a1a29-671e-4802-91d8-e3bb205e8588.jpg)

## PR Instruction:
- Issue will be assigned on a first come first serve basis.
- If you are thinking to make a pr then at first be sure to get assigned.
- before pushing your PR please make sure to fetch upstream.
- your pr should be pushed on the `develop` branch only.
- try to complete your assigned task within 3 to 5 days and if you need more time then please let me know. As the program has limited time only so please try to complete as fast as you can.
- With your PR try to send a screenshot or screen recording of your work

**Comment by SiddyDevelops** [comment]
Hello, I would like to resolve this issue, can you please assign this to me? Thank you.

**Comment by HeySitam** [comment]
sure go for it.

**Comment by SiddyDevelops** [comment]
Hello sir, I have created a PR #55 along with Screenshot, please review it. Thank you.
