### ISSUE TITLE
Remove hardcoded strings from xml file

### ISSUE THREAD

**Issue by HeySitam** [HeySitam/CovidHelp#6]
- Instead of hardcoded string save the string in the string.xml file and then use it using @string resource.

**Comment by KarandeepSingh15** [comment]
Hey @sitamadex11 ,
Can you Assign this to me?

**Comment by Rishavgupta12345** [comment]
can i do this ?

**Comment by HeySitam** [comment]
@Rishavgupta12345 bro I will soon create many issues then I will assign you. @GeorgeET15 has already given the pr. please have patience and give me some time.
