### ISSUE TITLE
Hide Keyboard when clicked in  the background

### ISSUE THREAD

**Issue by cdhiraj40** [HeySitam/CovidHelp#60]
Activities do not support closing the keyboard when clicking in the background

as you can see the keyboard takes alot of area in the activity, its better to hide when clicked outside so that user can fill its details properly.

https://user-images.githubusercontent.com/75211982/135877212-3dd88632-0a06-40ac-8778-a2de295d0c56.mp4

**Comment by HeySitam** [comment]
@cdhiraj40 THANKS FOR CREATING THE ISSUE. YOU CAN START WORKING.
