### ISSUE TITLE
UI: use different suitable icons for different cities.

### ISSUE THREAD

**Issue by HeySitam** [HeySitam/CovidHelp#61]
## Description:
- Here all the used icons are the same icon. Use some different appropriate icons for different cities. Inside `Resources` section.
## Existing UI :
![cities](https://user-images.githubusercontent.com/76570320/135977505-df14bf8d-ae6b-42c8-ab5d-1dfb74500828.jpg)

## PR Instruction:
- Issue will be assigned on a first come first serve basis.
- If you are thinking to make a pr then at first be sure to get assigned.
- before pushing your PR please make sure to fetch upstream.
- your pr should be pushed on the `develop` branch only.
- try to complete your assigned task within 3 to 5 days and if you need more time then please let me know. As the program has limited time only so please try to complete as fast as you can.
- With your PR try to send a screenshot or screen recording of your work

**Comment by Zaraki596** [comment]
I would like to take this up. Assign me this one

**Comment by HeySitam** [comment]
Sure

**Comment by Zaraki596** [comment]
Hey @sitamadex11  can I change **Thane** to **Jaipur** as there is no city related to Rajasthan. Plus can't find a proper skyline from the thane to match with other city skyline icons colour?

**Comment by HeySitam** [comment]
Sure. Then please make changes in the code accordingly.

**Comment by Zaraki596** [comment]
yeah definitely

**Comment by Zaraki596** [comment]
Added PR please review and check.
