### ISSUE TITLE
UI: Update the UI of the option selection page

### ISSUE THREAD

**Issue by HeySitam** [HeySitam/CovidHelp#63]
## Description:
- Update the UI of the option selection page in the `Twitter Help` section. Make it more attractive.
## Existing UI :
![Options](https://user-images.githubusercontent.com/76570320/135988057-2daab7e6-4073-4d7f-a4ab-071e0c585bad.jpg)

## PR Instruction:
- Issue will be assigned on a first come first serve basis.
- If you are thinking to make a pr then at first be sure to get assigned.
- before pushing your PR please make sure to fetch upstream.
- your pr should be pushed on the `develop` branch only.
- try to complete your assigned task within 3 to 5 days and if you need more time then please let me know. As the program has limited time only so please try to complete as fast as you can.
- With your PR try to send a screenshot or screen recording of your work

**Comment by Rarj** [comment]
Hi @sitamadex11, can i contribute in your antoher issue? I mean this one. If you open with this, feel free to assign me😁
Cheers!🍺

**Comment by rishuyadav** [comment]
hey, @sitamadex11 Can you explain a bit about what do you mean particularly, How can it be made more attractive? Which all areas have a scope of improvement, the UI now looks clean and simple let me know which all widgets can i style or make changes in

**Comment by HeySitam** [comment]
@Rarj  yes you can.
@rishuyadav yeah, you are right that the UI is already clean. simply I have created this issue to make the Ui more attractive if someone can as a `good first issue` to help you all.

**Comment by HeySitam** [comment]
sorry @Rarj and @rishuyadav for the late reply.

**Comment by Rarj** [comment]
@sitamadex11 no worries. I will work with this issue first than the other one.

**Comment by HeySitam** [comment]
@Rarj @rishuyadav  please join our group for discussion.
[CLICK HERE](https://chat.whatsapp.com/JXYziNoD3lD9RWQwD3VyEe) TO JOIN.

**Comment by Rarj** [comment]
> @Rarj @rishuyadav please join our group for discussion. [CLICK HERE](https://chat.whatsapp.com/JXYziNoD3lD9RWQwD3VyEe) TO JOIN.

yeah sure. thanks to inviting me!

**Comment by AasthaSinha2002** [comment]
> @Rarj yes you can. @rishuyadav yeah, you are right that the UI is already clean. simply I have created this issue to make the Ui more attractive if someone can as a `good first issue` to help you all.

I would like to work on this too could you assign me this ?
