### ISSUE TITLE
adding  custom icon from eye-icon(default) for hide-show password in login/signup activity

### ISSUE THREAD

**Issue by cdhiraj40** [HeySitam/CovidHelp#65]
Currently, the login/sign up activity doesn't have a hide-show password icon
login
![image](https://user-images.githubusercontent.com/75211982/136006409-2ea4c33d-4fb7-4275-82e8-28f6f5ea5e38.png)

signup
![image](https://user-images.githubusercontent.com/75211982/136006302-7ffc8596-a130-4390-91d9-e6a2d9f6a46d.png)

**Comment by HeySitam** [comment]
sure go for it.
