### ISSUE TITLE
UI: Donation page UI update

### ISSUE THREAD

**Issue by HeySitam** [HeySitam/CovidHelp#66]
## Description:
- Update the UI of the `Donate Here` section. Make it more attractive.
- You change the overall UI, except the Recycler View.
## Existing UI :
![donation page](https://user-images.githubusercontent.com/76570320/136086393-2b173c19-d68b-41f0-983f-51cc1bae5392.jpg)

## PR Instruction:
- Issue will be assigned on a first come first serve basis.
- If you are thinking to make a pr then at first be sure to get assigned.
- before pushing your PR please make sure to fetch upstream.
- your pr should be pushed on the `develop` branch only.
- try to complete your assigned task within 3 to 5 days and if you need more time then please let me know. As the program has limited time only so please try to complete as fast as you can.
- With your PR try to send a screenshot or screen recording of your work

**Comment by Rarj** [comment]
Hi @sitamadex11, i will work with this issue depend on your desciption 😄 
would you like to assign this work to me?

**Comment by HeySitam** [comment]
Sure.

**Comment by Rarj** [comment]
Hi @sitamadex11 , I have been created PR about Update Donation UI 😄 you can check my work. 
Thank you.
