### ISSUE TITLE
UI: Update the UI of the home page

### ISSUE THREAD

**Issue by HeySitam** [HeySitam/CovidHelp#68]
## Description:
- Update the UI of the `Home` section. Make it more attractive.
- Please send a screenshot of your design.
- If you want to make UI design only, also welcome. In this case please share your figma design link.
## Existing UI :
![home page](https://user-images.githubusercontent.com/76570320/136088799-08b81aeb-7214-4eb5-8def-862e16d8bd0c.jpg)

## PR Instruction:
- Issue will be assigned on a first come first serve basis.
- If you are thinking to make a pr then at first be sure to get assigned.
- before pushing your PR please make sure to fetch upstream.
- your pr should be pushed on the `develop` branch only.
- try to complete your assigned task within 3 to 5 days and if you need more time then please let me know. As the program has limited time only so please try to complete as fast as you can.
- With your PR try to send a screenshot or screen recording of your work

**Comment by SiddyDevelops** [comment]
I would like to work on this issue, can you please assign it to me? Thank you

**Comment by HeySitam** [comment]
@SiddyDevelops sure go for it.

**Comment by HeySitam** [comment]
Are you going to make changes in the code or going to make UI design in figma?

**Comment by SiddyDevelops** [comment]
I'll directly make changes in the XML, do you want to keep the black and white theme or can I change the theme to some more attractive colors ?

**Comment by HeySitam** [comment]
then please fetch the upstream. Change which is suitable with the splash screen. But don't use too much color. Try to manipulate with black and white theme

**Comment by SiddyDevelops** [comment]
Okay, I'll stick to splash screen theme, thank you.

**Comment by SiddyDevelops** [comment]
@sitamadex11 Sir do you like this:
I have changed background to a softer color, if you want I can choose a soft-black color.
<img height=600px src="https://user-images.githubusercontent.com/72121163/136149723-e0445347-4551-4934-b4dd-cf984bd16b18.jpg" />

**Comment by SiddyDevelops** [comment]
@sitamadex11 Sir do you like this:
I have changed background to a softer color, if you want I can choose a soft-black color.
<img height=600px src="https://user-images.githubusercontent.com/72121163/136149723-e0445347-4551-4934-b4dd-cf984bd16b18.jpg" />

**Comment by HeySitam** [comment]
Yup nice work. Please send the PR then.

**Comment by SiddyDevelops** [comment]
@sitamadex11 Sir I have generated a PR #75. Please review it, thank you.
