### ISSUE TITLE
UI: Add a scroll view in covid tracker section

### ISSUE THREAD

**Issue by HeySitam** [HeySitam/CovidHelp#69]
## Description:
- Make the borderd section scrollable.
## The underlined section :

![Covid Tracker](https://user-images.githubusercontent.com/76570320/136089917-435cf52c-63f4-4169-aaf1-ffddbecdaa01.jpg)

## PR Instruction:
- Issue will be assigned on a first come first serve basis.
- If you are thinking to make a pr then at first be sure to get assigned.
- before pushing your PR please make sure to fetch upstream.
- your pr should be pushed on the `develop` branch only.
- try to complete your assigned task within 3 to 5 days and if you need more time then please let me know. As the program has limited time only so please try to complete as fast as you can.
- With your PR try to send a screenshot or screen recording of your work

**Comment by PranavVyas20** [comment]
I want to work on this one, can you assign me please ?

**Comment by HeySitam** [comment]
sure go for it.

**Comment by PranavVyas20** [comment]
> sure go for it.

Is this ok ?

https://user-images.githubusercontent.com/90063033/136273647-7a4bfdbe-ab47-43f0-9e78-15f722a0333a.mp4

**Comment by PranavVyas20** [comment]
@sitamadex11 I have opened a PR kindly review it
