### ISSUE TITLE
UI enhancement: Change the state selection spinner UI in Covid tracker section.

### ISSUE THREAD

**Issue by HeySitam** [HeySitam/CovidHelp#7]
## In this section, it is not cleared to the user that we can see state-wise covid update also. So please modify and enhance the UI so that users can understand it.

# Before Click :
![1](https://user-images.githubusercontent.com/76570320/135517612-bc987dd5-ec31-4126-ba42-b1dff739358b.jpg)

# After Click :
![2](https://user-images.githubusercontent.com/76570320/135517691-a90d4b91-99ee-4368-bb49-468e2d7c9937.jpg)

 ## So please modify and enhance the UI so that users can understand it.

**Comment by rishuyadav** [comment]
Hey @sitamadex11 I would like to take up this issue, can u please assign it to me 
Thanks

**Comment by HeySitam** [comment]
sure go for it.

**Comment by rishuyadav** [comment]
Hey @sitamadex11 I have done the required UI Changes, spanner looks quite good now and easily understandable for the user.
