### ISSUE TITLE
Sending email for Feedback/Queries doesn't work

### ISSUE THREAD

**Issue by cdhiraj40** [HeySitam/CovidHelp#74]
https://user-images.githubusercontent.com/75211982/136219710-d0bd29d4-ec9f-4cbd-b3bb-813ad0ca28a6.mp4

**Comment by cdhiraj40** [comment]
this issue is probably happening because of this
 ```intent.resolveActivity(packageManager) != null ``` as its always getting passed as null
  I don't have much understanding about what it does but I have changed the code and tried and it works perfectly in the phones who have Gmail client apps otherwise it gives toast errors.
  if you @sitamadex11 I can make PR for this :)

**Comment by HeySitam** [comment]
Thank you for identifying this issue. actually, I have already created an issue with this problem #23. Yeah if you have done it already then feel free to push the PR
