### ISSUE TITLE
Old Closing Keyboard approach is causing Problems in Login/Sign up screen

### ISSUE THREAD

**Issue by cdhiraj40** [HeySitam/CovidHelp#83]
Some time ago I implemented the closing Keyboard method and it worked fine in my opinion but today when I went to login screen for testing something I found some bug which was not pretty annoying and I take all fault for that. 
Sorry, @sitamadex11 I would like to rectify the problem, and this time I have checked a lot, and please check too.
I will give recordings below.

old:

https://user-images.githubusercontent.com/75211982/136546431-b566dd10-4371-4221-92c8-1a3c9ae2a962.mp4

new:

https://user-images.githubusercontent.com/75211982/136546463-15d5148b-a037-44ac-8382-df359484785b.mp4

**Comment by cdhiraj40** [comment]
I hope you @sitamadex11  give me chance to rectify the problem and again sorry for the implementation. I should have tested one more time :/

**Comment by HeySitam** [comment]
okk sure go for it.
