### ISSUE TITLE
Clicking on Add Yourself as Volunteer doesnt take to proper Activity/fragment

### ISSUE THREAD

**Issue by cdhiraj40** [HeySitam/CovidHelp#86]
https://user-images.githubusercontent.com/75211982/136657517-d2f9ca0f-611c-4ec8-b295-2a2912134347.mp4

**Comment by cdhiraj40** [comment]
hey @sitamadex11 I'm not sure but can we even go to directly add yourself as a volunteer using ``` fragmentTransaction ``` ?

**Comment by HeySitam** [comment]
Actually, the idea is to add yourself as a volunteer you need to click on the `floating action button`. You can do one thing that what ever I the code base is to add yourself as a volunteer in the `floating action button`  simply use it in the menu item of the nav drawer.

**Comment by cdhiraj40** [comment]
> Actually, the idea is to add yourself as a volunteer you need to click on the `floating action button`. You can do one thing that whatever the code base is to add yourself as a volunteer in the `floating action button`  simply use it in the menu item of the nav drawer.

okay sure I will give it a try, you can assign me :)

**Comment by HeySitam** [comment]
SURE.

**Comment by HeySitam** [comment]
@cdhiraj40 please join our group for discussion. 
[CLICK HERE](https://chat.whatsapp.com/JXYziNoD3lD9RWQwD3VyEe) TO JOIN.

**Comment by anamansari062** [comment]
@sitamadex11 I would like to contribute and resolve this issue

**Comment by cdhiraj40** [comment]
@sitamadex11 I think I have contributed enough to not take  ``` good first issues ```  from people who are just starting to contribute to this repository, so on that thought I have unassigned myself, Hope you don't mind :)

**Comment by HeySitam** [comment]
@anamansari062 sure you can start working.

**Comment by HeySitam** [comment]
> @sitamadex11 I think I have contributed enough to not take `good first issues` from people who are just starting to contribute to this repository, so on that thought I have unassigned myself, Hope you don't mind :)

No issues bro. Thank you for helping others.

**Comment by anamansari062** [comment]
@sitamadex11 I resolved the error, can you please check

**Comment by HeySitam** [comment]
@anamansari062 Please send the PR.
