### ISSUE TITLE
Correcting the error message.

### ISSUE THREAD

**Issue by AasthaSinha2002** [HeySitam/CovidHelp#87]
During the signup, the error message displayed has a wrong spelling.  "Internaet"
Attaching the error message below

![image](https://user-images.githubusercontent.com/74906694/136666648-b7745a70-8f06-43ea-82cc-373d6819b6bc.png)

**Comment by AasthaSinha2002** [comment]
i would like to resolve this. 
please assign me

**Comment by AasthaSinha2002** [comment]
@sitamadex11

**Comment by AasthaSinha2002** [comment]
@sitamadex11 please look into this

**Comment by HeySitam** [comment]
Sorry for delay.

**Comment by AasthaSinha2002** [comment]
Thanks for review and merging.

From: Sitam Sardar ***@***.***>
Date: Monday, 11 October 2021 at 6:43 PM
To: sitamadex11/CovidHelp ***@***.***>
Cc: AASTHA SINHA ***@***.***>, Assign ***@***.***>
Subject: Re: [sitamadex11/CovidHelp] Correcting the error message. (#87)

Sorry for delay.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://ind01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsitamadex11%2FCovidHelp%2Fissues%2F87%23issuecomment-940019400&data=04%7C01%7C%7C02d95008d84049182e6108d98cb8ead3%7C2c5bdaf48ff24bd9bd547c50ab219590%7C0%7C0%7C637695548105926291%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fHKGF9VneVRxDRWR58Osiuz1RCjrQk6U9li4RUBje0I%3D&reserved=0>, or unsubscribe<https://ind01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAR3PYRVABNZHPJ7TQW7M4VDUGLPHNANCNFSM5FVOQO6A&data=04%7C01%7C%7C02d95008d84049182e6108d98cb8ead3%7C2c5bdaf48ff24bd9bd547c50ab219590%7C0%7C0%7C637695548105936247%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=m%2B3zXPyGOa24RwWwpCo3qrCR8ACmhu5%2B7YEvT9VEBBQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://ind01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C02d95008d84049182e6108d98cb8ead3%7C2c5bdaf48ff24bd9bd547c50ab219590%7C0%7C0%7C637695548105936247%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2Fid%2FnDGuwC0FKsyadnCZvBk%2FJC7slzb7DMk6lvpG9HA%3D&reserved=0> or Android<https://ind01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C02d95008d84049182e6108d98cb8ead3%7C2c5bdaf48ff24bd9bd547c50ab219590%7C0%7C0%7C637695548105936247%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tEjJYu13ABLhAZBnTc9zPhDtyfyBrpza4LFZaLQzZgo%3D&reserved=0>.
